In [1]:
import math

import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
from os.path import join
import math
import pickle
import time
from utilities import runQueryDTheta, loadData, donor_acceptor_dist
%matplotlib widget

dataPath = r"C:\Users\ashamail\Box\Shared Materials_Abdullah_Hasan\Abdullah Data\allAtomsWithRings.csv"
savePath = r"C:\Users\ashamail\Desktop\drug-polymers\adbis extension\data\ellipsoids"
savepathDrive = r"C:\Users\ashamail\OneDrive - Iowa State University\Molecular Simulation Data\adbis extension data"
oxygenPath = r"C:\Users\ashamail\OneDrive - Iowa State University\Molecular Simulation Data\Text Data Files\flavanone_R1_os_0-200K.csv"
oxygen_location = r"C:\Users\ashamail\Desktop\data\os_200_1.txt"
nitrogenPath = r"C:\Users\ashamail\Desktop\data\nitrogen200k.txt"



In [2]:
data = pd.read_csv(dataPath)
# oxygen = pd.read_csv(oxygenPath, header=None)
# oxygen = oxygen.rename(columns={0: "x", 1: "y", 2: "z"})
oxygen = loadData(oxygen_location)
nitrogen = loadData(nitrogenPath)
df = pd.read_csv(join(savepathDrive, "min_z_points.csv"))

# rfl1path = r"C:\Users\ashamail\OneDrive - Iowa State University\Molecular Simulation Data\Text Data Files\RFL1 Trajectory\rfl1_200k_0.txt"
PSP = 44
# rfl1 = loadData(rfl1path)

In [5]:
a, b = donor_acceptor_dist(oxygen[:,0,:], nitrogen, np.arange(200000)) #find timesteps for all 200k
print(a, a.shape)

[26005 32525 32537 32556 32557 32616 32617 32619 32620 32621 32622 32624
 32626 32627 32628 32629 32630 32631 32632 32715 32739 32792 32793 32794] (24,)


In [8]:
for x in np.arange(1, 7, 1):
    print(x, x*-1)


1 -1
2 -2
3 -3
4 -4
5 -5
6 -6


In [13]:
d_deltas = np.arange(1, 2, 1)
countPerDelta = {}
df["difference"] = df["min_z"].apply(lambda x: (x - PSP))
for delta in d_deltas:
    s1 = time.time()
    positive = delta
    negative = delta*-1
    more = df[df["difference"] < positive]
    less = df[df["difference"] < negative]
    print(more.shape)
    print(less.shape)
    print(more.shape[0] - less.shape[0])
    print(np.setdiff1d(more["timestep"], less["timestep"]).shape)

(87329, 3)
(80086, 3)
7243
(7243,)


In [20]:
# for all timesteps
# can also plot an instance using the line below
# plot_ell_and_plane(ell, points)
d_deltas = np.arange(1, 7, 1)
countPerDelta = {}
df["difference"] = df["min_z"].apply(lambda x: (x - PSP))
for delta in d_deltas:
    s1 = time.time()
    positive = delta
    negative = delta*-1
    more = df[df["difference"] < positive]
    less = df[df["difference"] < negative]
    # points_less_than_delta = df[df["difference"] < delta]
    timesteps = np.setdiff1d(more["timestep"], less["timestep"])
    print(delta, "timeframes", timesteps) #calculate ellipsoid and then calculate distance between min point and PSP using d_delte (1,2,3,4)
    # print(points_less_than_delta)
    print(delta, " pre-processing ", time.time() - s1)
    s = time.time()
    a, b = donor_acceptor_dist(oxygen[:,0,:], nitrogen, timesteps)
    # timesteps = runQueryDTheta(np.array(points_less_than_delta["timestep"]), oxygen, PSP) #for each d_delta instances, run the d_theta query
    # countPerDelta[delta] = a
    print(delta, a, a.shape, time.time() - s)

# for key, val in countPerDelta.items():
#     print(key, val.shape[0])

1 timeframes [ 17030  17186  17187 ... 199707 199708 199927]
1  pre-processing  0.014999628067016602
1 [] (0, 1) 1.8680105209350586
2 timeframes [ 11237  17027  17028 ... 199931 199989 199996]
2  pre-processing  0.015004396438598633
2 [] (0, 1) 3.564877510070801
3 timeframes [  2088  11237  11239 ... 199996 199997 199999]
3  pre-processing  0.016028881072998047


KeyboardInterrupt: 

In [16]:
# for all timesteps
# can also plot an instance using the line below
# plot_ell_and_plane(ell, points)
d_deltas = np.arange(-6, 7, 1)
countPerDelta = {}
df["difference"] = df["min_z"].apply(lambda x: (x - PSP))
for delta in d_deltas:
    s1 = time.time()
    points_less_than_delta = df[df["difference"] < delta]
    timesteps = np.array(points_less_than_delta["timestep"])
    print(timesteps.shape)
    print(points_less_than_delta.shape) #calculate ellipsoid and then calculate distance between min point and PSP using d_delte (1,2,3,4)
    # print(points_less_than_delta)
    print(delta, " pre-processing ", time.time() - s1)
    s = time.time()
    a, b = donor_acceptor_dist(oxygen[:,0,:], nitrogen, timesteps)
    # timesteps = runQueryDTheta(np.array(points_less_than_delta["timestep"]), oxygen, PSP) #for each d_delta instances, run the d_theta query
    countPerDelta[delta] = a
    print(delta, a.shape, time.time() - s)

# for key, val in countPerDelta.items():
#     print(key, val.shape[0])

(58717,)
(58717, 3)
-6  pre-processing  0.005997896194458008


KeyboardInterrupt: 

In [6]:
saveLocation = r"C:\Users\ashamail\OneDrive - Iowa State University\Molecular Simulation Data\adbis extension data\e_gatco data"

In [7]:
# generate data to save to measure space required
# d_deltas = [-4,-3,-2,-1,0,1,2,3,4]
# countPerDelta = {}
# oxygen[:,0,:].shape
toappend = np.arange(200000)
toappend = toappend.reshape(toappend.shape[0], 1)
rflOxygen = np.append(oxygen[:,0,:], toappend, axis = 1)
df["difference"] = df["min_z"].apply(lambda x: (x - PSP))
for delta in d_deltas:
    points_less_than_delta = df[df["difference"] < delta] #calculate ellipsoid and then calculate distance between min point and PSP using d_delte (1,2,3,4)
    # print(points_less_than_delta)
    timesteps = np.array(points_less_than_delta["timestep"])
    
    temp = rflOxygen[timesteps]
    np.savetxt(join(saveLocation, str(delta), "oxygen.csv"), temp, delimiter=",")
    tempnitrogen = nitrogen[timesteps]
    for i in range(216):
    #     nitrogen[:,i,:].shape
        nitrogeni = np.append(tempnitrogen[:,i,:], timesteps.reshape(timesteps.shape[0], 1), axis = 1)
        np.savetxt(join(saveLocation, str(delta), str(i)+"-nitrogen.csv"), nitrogeni, delimiter=",")
    
    print("done", delta)
    # s = time.time()
    # a, b = donor_acceptor_dist(oxygen[:,0,:], nitrogen, timesteps)
    # timesteps = runQueryDTheta(np.array(points_less_than_delta["timestep"]), oxygen, PSP) #for each d_delta instances, run the d_theta query
    # countPerDelta[delta] = a
    # print(delta, a.shape, time.time() - s)

done -7
done -6
done -5


In [24]:
timesteps

array([  2086,   2087,   2088, ..., 199997, 199998, 199999], dtype=int64)

array([[11.43114948, -2.25737381, 29.72561264],
       [11.61144924, -2.10746789, 29.7369957 ],
       [11.68274212, -2.47028089, 29.60742188],
       ...,
       [11.29133797, -2.08883071, 29.70737267],
       [11.17711544, -2.474231  , 29.7449398 ],
       [11.18099213, -1.90097368, 29.84999466]])

In [26]:
nitrogen[2086:2089][:,0]

array([[11.43114948, -2.25737381, 29.72561264],
       [11.61144924, -2.10746789, 29.7369957 ],
       [11.68274212, -2.47028089, 29.60742188]])

In [20]:
df["difference"] = df["min_z"].apply(lambda x: (x - PSP))
for delta in d_deltas:
    points_less_than_delta = df[df["difference"] < delta] #calculate ellipsoid and then calculate distance between min point and PSP using d_delte (1,2,3,4)
    # print(points_less_than_delta)
    timesteps = np.array(points_less_than_delta["timestep"])
    print(timesteps.shape)

(67654,)
(72008,)
(76202,)
(80086,)
(83740,)
(87329,)
(90942,)
(94642,)
(98099,)


In [16]:
for key, val in countPerDelta.items():
    print(key, val, val.shape)

4 [26005 32525 32537 32556 32557 32616 32617 32619 32620 32621 32622 32624
 32626 32627 32628 32629 32630 32631 32632 32715 32739 32792 32793 32794] (24,)
